on:
  push:
    branches:
      - main
      - 'feature/*'   # or '*' for all branches
      - feature
  pull_request:
    branches:
      - main
      - feature
      - 'feature/*'   # or '*' for all branches
  workflow_dispatch:

jobs:
  run-conda-script:
    runs-on: self-hosted  # 💻 This targets your laptop runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up conda environment
        shell: cmd
        run: |
          call C:\Users\basant.joshi\AppData\Local\anaconda3\condabin\conda.bat activate rag
          cd src
          pytest test
          
      - name: Print Conda Info
        shell: cmd
        run: |
          call C:\Users\basant.joshi\AppData\Local\anaconda3\condabin\conda.bat info
